import {writeFileSync,readFileSync,existsSync} from 'node:fs';
import YAML from 'yaml';
import {composeManifest} from '../infra/topology.mjs';
const content='# Generated by scripts/generate-compose.mjs. Dedicated local sandbox only; not production high availability.\n'+YAML.stringify(composeManifest());
if(process.argv.includes('--check')){
 if(!existsSync('compose.yaml')||readFileSync('compose.yaml','utf8')!==content)throw new Error('Compose output differs from its source topology. Run node scripts/generate-compose.mjs.');
}else writeFileSync('compose.yaml',content);
